# Spotify API Configuration
# Replace these values with your own Spotify API credentials
# Get them from: https://developer.spotify.com/dashboard

spotify.client.id=
spotify.client.secret=
spotify.redirect.uri=http://[::1]:8080/callback
